# GitHub Pages configuration

name: Element Algebra
description: 从零开始的代数几何教科书
version: 1.0.0

# Build settings  
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

# Include files
include:
  - _includes
  - _layouts

# GitHub Pages plugins
plugins:
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-relative-links
  - jekyll-default-layout
  - jekyll-titles-from-headings
